apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: chart
  namespace: default
spec:
  interval: 1m
  url: https://github.com/imnishantdevops/weatherservice1.git
  ref:
    branch: main
