apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weather-pod
  namespace: default
spec:
  interval: 5m
  releaseName: weather-pod
  chart:
    spec:
      chart: ./chart
      version: 3.0.0
      sourceRef:
        kind: GitRepository
        name: chart
        namespace: default
  values:
    replicaCount: 2
    image:
      repository: imnishantdevops/weather-forecast-app
      pullPolicy: IfNotPresent
      tag: "latest"
    service:
      type: NodePort
      port: 80
    env:
      API_KEY: "{{ .Values.env.API_KEY | default \"0463d36f8a64d3405f77ae069770d0a4\" }}"
      API_URL: "http://api.openweathermap.org/data/2.5/weather"
      Forecast_URL: "http://api.openweathermap.org/data/2.5/forecast"
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    tolerations:
      - key: "weather-app"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: DoesNotExist
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - weather-pod
            topologyKey: "kubernetes.io/hostname"
