apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weather-pod
  namespace: default
spec:
  interval: 5m
  releaseName: weather-pod
  chart:
    spec:
      chart: ./chart
      version: 3.1.2
      sourceRef:
        kind: GitRepository
        name: chart
        namespace: default
  values:
    replicaCount: 2
    image:
      repository: imnishantdevops/weather-forecast-app
      pullPolicy: IfNotPresent
      tag: "latest"
    service:
      type: NodePort
      port: 80
    env:
      API_URL: "http://api.openweathermap.org/data/2.5/weather"
      FORECAST_URL: "http://api.openweathermap.org/data/2.5/forecast"
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    tolerations:
      - key: "weather-app"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: DoesNotExist
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - weather-pod
            topologyKey: "kubernetes.io/hostname"

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: weather-pod-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather-pod
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
